---
- hosts: all
  vars_files:
    - ../extra-variables.yml
  roles: 
    - role: oci-rsa-ansible-base
      become: true
    - role: wazuh-cluster
      become: true
    - role: wazuh-ansible/wazuh-ansible/roles/wazuh/ansible-wazuh-manager
      become: true
    - role: wazuh-ansible/wazuh-ansible/roles/wazuh/ansible-filebeat-oss
      become: true
    - role: wazuh-logs
      become: true
