---
# tasks file for base
- name: activate epel
  ansible.builtin.lineinfile:
    path: /etc/yum.repos.d/oracle-epel-ol7.repo
    regexp: '^enabled=0'
    line: enabled=1
  become: true
- name: Install chrony
  package:
    name: chrony
    state: latest # noqa package-latest
  become: true
- name: Activate cron job to run Ansible
  ansible.builtin.cron:
    name: Schedule for Ansible
    minute: "*/15"
    job: "ANSIBLE_ROLES_PATH=/opt/oci-rsa/oci-rsa-ansible-bastion/.galaxy /usr/bin/ansible-playbook -i localhost, /opt/oci-rsa/oci-rsa-ansible-bastion/main.yml --connection=local"
  become: true
- name: Ensure chrony.conf has correct server
  ansible.builtin.lineinfile:
    path: /etc/chrony.conf
    regexp: '^server'
    line: 'server 169.254.169.254 iburst'
  become: true
  notify: 
    - Restart chronyd
- name: Install suricata
  package:
    name: suricata
    state: present # noqa package-latest
  become: true
- name: Update suricata rules
  ansible.builtin.command: /bin/suricata-update
  become: true
  args:
    creates: /var/lib/suricata/rules/suricata.rules
- name: deploy suricata sysconfig
  ansible.builtin.template:
    src: suricata.sysconfig.j2
    dest: /etc/sysconfig/suricata
    owner: root
    group: root
    mode: '0644'
  become: true
  notify: 
    - Restart suricata
- name: schedule suricata update
  ansible.builtin.cron:
    name: Schedule for suricata
    minute: "13"
    hour: "1"
    job: "/bin/suricata-update"
  become: true
- name: scanning deployment 
  meta: noop
- name: Install lynis
  package:
    name: lynis
    state: latest # noqa package-latest
  become: true
- name: Install nmap
  package:
    name: nmap
    state: latest # noqa package-latest
  become: true
- name: Install git
  package:
    name: git
    state: latest # noqa package-latest
  become: true
- name: Install scipag (from Github)
  ansible.builtin.git:
    repo: 'https://github.com/scipag/vulscan'
    dest: '/opt/scipag_vulscan'
  become: true
- name: schedule nmap scanner
  ansible.builtin.cron:
    name: Schedule for nmap scanner
    user: nobody
    minute: "23"
    hour: "3"
    job: '/usr/bin/nmap -Pn -sV --script=/opt/scipag_vulscan/vulscan.nse localhost | logger -t nmap_scipag_vulscan'
  become: true
- name: schedule lynis pentest
  ansible.builtin.cron:
    name: Schedule for lynis pentest
    user: root
    minute: "23"
    hour: "2"
    job: '/bin/lynis audit system --pentest'
  become: true