---
- name: Debian/Ubuntu | Install apt-transport-https and ca-certificates
  apt:
    name:
      - apt-transport-https
      - ca-certificates
    state: present
  register: kibana_installing_ca_package
  until: kibana_installing_ca_package is succeeded

- name: Debian/Ubuntu | Add Elasticsearch GPG key
  apt_key:
    url: "{{ elasticrepo.gpg }}"
    id: "{{ elasticrepo.key_id }}"
    state: present

- name: Debian/Ubuntu | Install Elastic repo
  apt_repository:
    repo: "deb {{ elasticrepo.apt }} stable main"
    state: present
    filename: 'elastic_repo_7'
    update_cache: true
  changed_when: false

- name: Debian/Ubuntu | Install Kibana
  apt:
    name: "kibana={{ elastic_stack_version }}"
    state: present
    cache_valid_time: 3600
  register: installing_kibana_package
  until: installing_kibana_package is succeeded
  tags: install
