---
- name: RedHat/CentOS/Fedora | Install Elastic repo
  yum_repository:
    name: elastic_repo_7
    description: Elastic repository for 7.x packages
    baseurl: "{{ elasticrepo.yum }}"
    gpgkey: "{{ elasticrepo.gpg }}"
    gpgcheck: true
  changed_when: false

- name: RedHat/CentOS/Fedora | Install Kibana
  package: name=kibana-{{ elastic_stack_version }} state=present
  register: installing_kibana_package
  until: installing_kibana_package is succeeded
  tags: install
